///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Sat Feb 20 2021 10:16 CST]
// Generate from:
//   [github.com/gxlb/cli/internal/gp/value.gp]
//   [github.com/gxlb/cli/value.gpg] [value_string]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2021 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Site    : https://github.com/vipally
// Version : 3.0.0.final
// 
///////////////////////////////////////////////////////////////////

package cli

import (
	"flag"
)

////////////////////////////////////////////////////////////////////////////////

// StringValue define a value of type string
type StringValue struct {
	Target      *string  // Target value pointer outside
	Default     string   // Default value
	DefaultText string   // Default value in help info
	Enums       []string // Enumeration of valid values
	Ranges      []string // [min,max,min,max...] ranges of valid values
	value       string   // The value from ENV of files
	hasBeenSet  bool
}

func (v *StringValue) IsSet() bool {
	return v.hasBeenSet
}

func (v *StringValue) Apply(f *Flag, set *flag.FlagSet) error {
	return nil
}

func (v *StringValue) String() string {
	return ""
}
