///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Sat Feb 20 2021 10:16 CST]
// Generate from:
//   [github.com/gxlb/cli/internal/gp/value.gp]
//   [github.com/gxlb/cli/value.gpg] [value_string_slice]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2021 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Site    : https://github.com/vipally
// Version : 3.0.0.final
// 
///////////////////////////////////////////////////////////////////

package cli

import (
	"flag"
	"fmt"
	"strconv"
	//"encoding/json"
	//"strings"
)

////////////////////////////////////////////////////////////////////////////////
// StringSliceSlice wraps []string to satisfy flag.Value
type StringSliceSlice struct {
	slice      []string
	hasBeenSet bool
}

// NewStringSliceSlice makes an *StringSliceSlice with default values
func NewStringSliceSlice(defaults ...string) *StringSliceSlice {
	return &StringSliceSlice{slice: append([]string{}, defaults...)}
}

// clone allocate a copy of self object
func (s *StringSliceSlice) clone() *StringSliceSlice {
	n := &StringSliceSlice{
		slice:      make([]string, len(s.slice)),
		hasBeenSet: s.hasBeenSet,
	}
	copy(n.slice, s.slice)
	return n
}

// TODO: Consistently have specific Set function for Int64 and Float64 ?
// Append directly adds an integer to the list of values
func (s *StringSliceSlice) Append(value ...string) {
	if !s.hasBeenSet {
		s.slice = []string{}
		s.hasBeenSet = true
	}

	s.slice = append(s.slice, value...)
}

// Set parses the value into an integer and appends it to the list of values
func (s *StringSliceSlice) Set(value string) error {
	if !s.hasBeenSet {
		s.slice = []string{}
		s.hasBeenSet = true
	}

	// if strings.HasPrefix(value, slPfx) {
	// 	// Deserializing assumes overwrite
	// 	_ = json.Unmarshal([]byte(strings.Replace(value, slPfx, "", 1)), &s.slice)
	// 	s.hasBeenSet = true
	// 	return nil
	// }

	tmp, err := strconv.ParseInt(value, 0, 64)
	if err != nil {
		return err
	}

	s.slice = append(s.slice, string(tmp))

	return nil
}

// String returns a readable representation of this value (for usage defaults)
func (s *StringSliceSlice) String() string {
	return fmt.Sprintf("%#v", s.slice)
}

// Serialize allows StringSliceSlice to fulfill Serializer
func (s *StringSliceSlice) Serialize() string {
	//TODO:
	// jsonBytes, _ := json.Marshal(s.slice)
	// return fmt.Sprintf("%s%s", slPfx, string(jsonBytes))
	return ""
}

// Value returns the slice of ints set by this flag
func (s *StringSliceSlice) Value() []string {
	return s.slice
}

// Get returns the slice set by this flag
func (s *StringSliceSlice) Get() interface{} {
	return *s
}

// StringSliceValue define a value of type *StringSliceSlice
type StringSliceValue struct {
	Target      *StringSliceSlice // Target value pointer outside
	Default     *StringSliceSlice // Default value
	DefaultText string            // Default value in help info
	Enums       []string          // Enumeration of valid values
	Ranges      []string          // [min,max,min,max...] ranges of valid values
	value       *StringSliceSlice // The value from ENV of files
	hasBeenSet  bool
}

func (v *StringSliceValue) IsSet() bool {
	return v.Value.hasBeenSet
}

func (v *StringSliceValue) Apply(f *Flag, set *flag.FlagSet) error {
	return nil
}

func (v *StringSliceValue) String() string {
	return ""
}
