///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Sat Feb 20 2021 09:24:53]
// Generate from:
//   [github.com/gxlb/cli/internal/gp/value.gp]
//   [github.com/gxlb/cli/value.gpg] [value_int]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2021 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Site    : https://github.com/vipally
// Version : 3.0.0.final
// 
///////////////////////////////////////////////////////////////////

package cli

////////////////////////////////////////////////////////////////////////////////

// IntValue define a value of type int
type IntValue struct {
	Value       int    // The value from ENV of files
	Target      *int   // Target set the outer value pointer
	Default     int    // Default value
	DefaultText string // Default value help info
	Enums       []int  // Enumeration of valid values
	Ranges      []int  // [min,max,min,max...] ranges of valid values
	hasBeenSet  bool
}
