///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/gxlb/gogp]
// Last update at: [Sat Feb 20 2021 12:24 CST]
// Generate from:
//   [github.com/gxlb/cli/internal/gp/value.gp]
//   [github.com/gxlb/cli/value.gpg] [value_int]
//
// Tool [github.com/gxlb/gogp] info:
// CopyRight 2021 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Site    : https://github.com/vipally
// Version : 3.0.0.final
// 
///////////////////////////////////////////////////////////////////

package cli

import (
	"flag"
	"fmt"
)

////////////////////////////////////////////////////////////////////////////////
// IntValue define a value of type GOGPElemType
type IntValue struct {
	Target      *int   // Target value pointer outside
	Default     int    // Default value
	DefaultText string // Default value in help info
	Enums       []int  // Enumeration of valid values
	Ranges      []int  // {[min,max),[min,max),[min...)} ranges of valid values
	value       int    // The value from ENV of files
	hasBeenSet  bool
	flag        *Flag //pointer of flag
}

// Init verify and init the value by ower flag
func (v *IntValue) Init(f *Flag) error {
	v.flag = f
	if l := len(v.Enums); l > maxSliceLen {
		return fmt.Errorf("flag %s.Enums too long: %d/%d", v.flag.logicName, l, maxSliceLen)
	}
	if l := len(v.Ranges); l > maxSliceLen {
		return fmt.Errorf("flag %s.Ranges too long: %d/%d", v.flag.logicName, l, maxSliceLen)
	}
	return nil
}

// IsSet check if value is setted
func (v *IntValue) IsSet() bool {
	return v.hasBeenSet
}

// Apply coordinate the value to flagset
func (v *IntValue) Apply(set *flag.FlagSet) error {
	return nil
}

// String return the value for view
func (v *IntValue) String() string {
	return ""
}

// ValidateValues verify if all values was valid
func (v *IntValue) ValidateValues() error {
	return v.validateValues(v.value)
}

//for default value verify
func (v *IntValue) validateValues(values int) error {
	return v.validValue(values)
}

// check if value if valid for this flag
func (v *IntValue) validValue(value int) error {
	f := v.flag
	if len(v.Enums) > 0 {
		found := false
		for _, v := range v.Enums {
			if value == v {
				found = true
				break
			}
		}
		if !found {
			return fmt.Errorf("flag %s value %v out of Enums: %v", f.logicName, value, v.Enums)
		}
	}
	if len(v.Ranges) > 0 {
		found := false
		for i := 0; i < len(v.Ranges); i++ {
			min := v.Ranges[i]
			max := min
			if i++; i < len(v.Ranges) {
				max = v.Ranges[i]
			}
			if value >= min && value < max {
				found = true
				break
			}
		}
		if !found {
			return fmt.Errorf("flag %s value %v out of Ranges: %v", f.logicName, value, v.Enums)
		}
	}
	return nil
}

var _ Value = (*IntValue)(nil) //for interface verification only
